In [1]:
import numpy
import pandas
import joblib
import json
import seaborn

import sklearn

%matplotlib inline

# Instructions

- Read **the test data** from the CSV file and properly set the index
- Load the trained model

,duration,credit_amount,age,checking_status,credit_history,purpose,savings_status,employment,personal_status,other_parties,...,other_payment_plans,housing,job,own_telephone,foreign_worker,installment_commitment,residence_since,existing_credits,num_dependents,label
id,,,,,,,,,,,,,,,,,,,,,
993,36.0,3959.0,30,1.0,2.0,5.0,1.0,0.0,0.0,0.0,...,0.0,2.0,3.0,1.0,1.0,3.0,2.0,0.0,0.0,0.0
859,9.0,3577.0,26,0.0,2.0,8.0,2.0,2.0,0.0,2.0,...,0.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
298,18.0,2515.0,43,0.0,2.0,5.0,1.0,2.0,0.0,0.0,...,0.0,2.0,2.0,1.0,1.0,2.0,3.0,0.0,0.0,0.0
553,12.0,1995.0,27,2.0,0.0,8.0,2.0,1.0,0.0,0.0,...,0.0,2.0,2.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0
672,60.0,10366.0,42,0.0,2.0,8.0,1.0,4.0,0.0,0.0,...,0.0,2.0,3.0,1.0,1.0,1.0,3.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,12.0,3017.0,34,2.0,2.0,5.0,1.0,1.0,3.0,0.0,...,0.0,1.0,3.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0
356,12.0,2331.0,49,0.0,0.0,6.0,0.0,4.0,0.0,1.0,...,0.0,2.0,2.0,1.0,1.0,0.0,3.0,0.0,0.0,0.0
2,12.0,2096.0,49,0.0,0.0,1.0,1.0,3.0,0.0,0.0,...,0.0,2.0,1.0,0.0,1.0,1.0,2.0,0.0,1.0,0.0
478,12.0,1037.0,39,2.0,2.0,9.0,2.0,3.0,0.0,0.0,...,0.0,2.0,1.0,0.0,1.0,2.0,3.0,0.0,0.0,0.0
695,6.0,1236.0,50,0.0,2.0,7.0,3.0,2.0,0.0,0.0,...,0.0,1.0,2.0,0.0,1.0,1.0,3.0,0.0,0.0,0.0

KNeighborsClassifier()

# Instructions
- Calculate and add the `prediction` column to the dataframe of test data
- Write the dataframe to `./results/predictions.test.csv`

,duration,credit_amount,age,checking_status,credit_history,purpose,savings_status,employment,personal_status,other_parties,...,housing,job,own_telephone,foreign_worker,installment_commitment,residence_since,existing_credits,num_dependents,label,prediction
id,,,,,,,,,,,,,,,,,,,,,
993,36.0,3959.0,30,1.0,2.0,5.0,1.0,0.0,0.0,0.0,...,2.0,3.0,1.0,1.0,3.0,2.0,0.0,0.0,0.0,0.0
859,9.0,3577.0,26,0.0,2.0,8.0,2.0,2.0,0.0,2.0,...,1.0,2.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
298,18.0,2515.0,43,0.0,2.0,5.0,1.0,2.0,0.0,0.0,...,2.0,2.0,1.0,1.0,2.0,3.0,0.0,0.0,0.0,0.0
553,12.0,1995.0,27,2.0,0.0,8.0,2.0,1.0,0.0,0.0,...,2.0,2.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0
672,60.0,10366.0,42,0.0,2.0,8.0,1.0,4.0,0.0,0.0,...,2.0,3.0,1.0,1.0,1.0,3.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,12.0,3017.0,34,2.0,2.0,5.0,1.0,1.0,3.0,0.0,...,1.0,3.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0
356,12.0,2331.0,49,0.0,0.0,6.0,0.0,4.0,0.0,1.0,...,2.0,2.0,1.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0
2,12.0,2096.0,49,0.0,0.0,1.0,1.0,3.0,0.0,0.0,...,2.0,1.0,0.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0
478,12.0,1037.0,39,2.0,2.0,9.0,2.0,3.0,0.0,0.0,...,2.0,1.0,0.0,1.0,2.0,3.0,0.0,0.0,0.0,0.0
695,6.0,1236.0,50,0.0,2.0,7.0,3.0,2.0,0.0,0.0,...,1.0,2.0,0.0,1.0,1.0,3.0,0.0,0.0,0.0,0.0

# Instructions
- Use `sklearn.metrics.confusion_matrix` to calculate the confusion matrix

array([[144,  30],
       [ 59,  14]])

# Instructions

- Use `sklearn.metrics.classification_report` to print the classification report
- Now, **manually fill** the following metrics `y=1` and put them in a Python dictionary
- The expected output should look like:

```
scores = {
     'true_positive': 8,
     'true_negative': 163,
     'false_negative': 11,
     'false_positive': 65,
     'accuracy': 0.692,
     'precision': 0.421,
     'recall': 0.109,
     'support': 73,
     'f1-score': 0.173
}
```


- Use `json.dump` to save the output to  `./results/scores.test.json`

                  0.0        1.0  accuracy   macro avg  weighted avg
precision    0.709360   0.318182  0.639676    0.513771      0.593748
recall       0.827586   0.191781  0.639676    0.509684      0.639676
f1-score     0.763926   0.239316  0.639676    0.501621      0.608879
support    174.000000  73.000000  0.639676  247.000000    247.000000