In [1]:
import pandas
import joblib
import json
import sklearn

%matplotlib inline

# Instructions

- Read **the test data** from the CSV file and properly set the index
- Load the trained model

,anaemia,diabetes,high_blood_pressure,sex,smoking,death_event,age,creatinine_phosphokinase,ejection_fraction,platelets,serum_creatinine,serum_sodium,time
id,,,,,,,,,,,,,
206,1.0,0.0,0.0,0.0,0.0,0.0,40.000,101.0,40.0,226000.0,0.8,141.0,187.0
188,1.0,1.0,1.0,0.0,0.0,0.0,60.667,151.0,40.0,201000.0,1.0,136.0,172.0
12,1.0,0.0,0.0,1.0,0.0,1.0,45.000,981.0,30.0,136000.0,1.1,137.0,11.0
219,0.0,1.0,1.0,0.0,0.0,0.0,55.000,582.0,35.0,371000.0,0.7,140.0,197.0
237,0.0,0.0,0.0,1.0,0.0,0.0,70.000,232.0,30.0,173000.0,1.2,132.0,210.0

LogisticRegression(fit_intercept=False, penalty=None, random_state=0)


# Instructions

- Calculate and add the `prediction` column to the dataframe of test data
- Write the dataframe to `./results/predictions.test.csv`

,anaemia,diabetes,high_blood_pressure,sex,smoking,death_event,age,creatinine_phosphokinase,ejection_fraction,platelets,serum_creatinine,serum_sodium,time,prediction
id,,,,,,,,,,,,,,
206,1.0,0.0,0.0,0.0,0.0,0.0,40.000,101.0,40.0,226000.0,0.8,141.0,187.0,0.0
188,1.0,1.0,1.0,0.0,0.0,0.0,60.667,151.0,40.0,201000.0,1.0,136.0,172.0,0.0
12,1.0,0.0,0.0,1.0,0.0,1.0,45.000,981.0,30.0,136000.0,1.1,137.0,11.0,1.0
219,0.0,1.0,1.0,0.0,0.0,0.0,55.000,582.0,35.0,371000.0,0.7,140.0,197.0,0.0
237,0.0,0.0,0.0,1.0,0.0,0.0,70.000,232.0,30.0,173000.0,1.2,132.0,210.0,0.0

# Instructions

- Use `sklearn.metrics.classification_report` to print the classification report
- Now, *manually create* a Python dictionary with the following metrics of the class `y=1`:
    - `'accuracy'`
    - `'precision'`
    - `'recall'`
    - `'f1-score'`
- Use `json.dump` to save the output to  `./results/scores.test.json`

                 0.0        1.0  accuracy  macro avg  weighted avg
precision   0.745763   0.733333  0.743243   0.739548      0.741396
recall      0.916667   0.423077  0.743243   0.669872      0.743243
f1-score    0.822430   0.536585  0.743243   0.679508      0.721998
support    48.000000  26.000000  0.743243  74.000000     74.000000

{'accuracy': 0.743, 'precision': 0.733, 'recall': 0.423, 'f1-score': 0.536}